AnsibleSolution/Models/MyEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnsibleSolution.Models
{
    public class MyEntity
    {
        public int MyEntityId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
    }
}

AnsibleSolution/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AnsibleSolution.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AnsibleSolution/Controllers/MyEntityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnsibleSolution.Abstractions;
using AnsibleSolution.Models;
using Microsoft.AspNetCore.Mvc;

namespace AnsibleSolution.Controllers
{
    /// <summary>
    /// MyEntity Controller
    /// Contains all API endpoints to process for getting and setting MyEntity objects.
    /// </summary>
    public class MyEntityController : Controller
    {
        private IMyEntityService _myEntityService;

        public MyEntityController(IMyEntityService myEntityService)
        {
            _myEntityService = myEntityService;
        }

        /// <summary>
        ///     Gets all MyEntities from repository
        /// </summary>
        /// <returns>List<MyEntity></returns>
        public IActionResult All()
        {
            var entities = _myEntityService.GetAllEntities();

            return View(entities);
        }

        /// <summary>
        ///     Gets a MyEntity by Id
        /// </summary>
        /// <param name="id">Id of MyEntity object</param>
        /// <returns>MyEntity</returns>
        public IActionResult Id(int id)
        {
            var entity = _myEntityService.GetEntityById(id);

            return View(entity);
        }

        /// <summary>
        ///     Gets Add View with form to create a new MyEntity
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        ///     Adds a new MyEntity to repository
        /// </summary>
        /// <param name="entity">MyEntity to be added</param>
        /// <returns>View</returns>
        [HttpPost]
        public IActionResult Add(MyEntity entity)
        {
            _myEntityService.AddEntity(entity);

            return RedirectToAction(@"../Home/Index");
        }
    }
}

AnsibleSolution/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Home Page</h2>

<p>.Net project that contains a simple front end with a back-end REST api.</p>
<p>Built with AspNet.Mvc Core 2.0</p>

AnsibleSolution/Views/MyEntity/Add.cshtml
@model AnsibleSolution.Models.MyEntity

<h2>Add Entity</h2>

<form method="post">
    <div class="form-group">
        <label>Name</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label>Details</label>
        <input asp-for="Details" class="form-control" />
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

AnsibleSolution/Views/MyEntity/All.cshtml
@model List<AnsibleSolution.Models.MyEntity>

<h2>All Entities</h2>

<table class="table table-condensed">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Details</th>
    </tr>
    @foreach (var entity in Model)
    {
    <tr>
        <td>@entity.MyEntityId</td>
        <td>@entity.Name</td>
        <td>@Html.ActionLink("More...", "Id", "MyEntity", new { id = entity.MyEntityId })</td>
    </tr>
    }
</table>

AnsibleSolution/Views/MyEntity/Id.cshtml
@model AnsibleSolution.Models.MyEntity

<h2>MyEntity Details</h2>

<p>Id: @Model.MyEntityId</p>

<p>Name: @Model.Name</p>

<p>Details: @Model.Details</p>

AnsibleSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">AnsibleTest</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                    <li><a asp-action="All" asp-controller="MyEntity">All Entities</a></li>
                    <li><a asp-action="Add" asp-controller="MyEntity">Create Entities</a></li>
                </ul>
            </div>
        </nav>
        <div class="panel panel-default">
            <div class="panel-body">
                @RenderBody()
            </div>
            <footer class="panel-footer">
                <p>Luis Del Valle. <a href="mailto:luis@luis-delvalle.com">Contact</a></p>
            </footer>
        </div>
    </div>
</body>
</html>